package com.example.project_group8;

public class Database_de {
    Integer[] player ={
            R.drawable.abby_dahlkemper,
            R.drawable.alexia_putellas,
            R.drawable.alphonso_davies,
            R.drawable.amel_majri,
            R.drawable.asisat_oshoala,
            R.drawable.beth_england,
            R.drawable.bruno_fernandes,
            R.drawable.ciro_immobile,
            R.drawable.cristiana_girelli,
            R.drawable.cristiano_ronaldo,
            R.drawable.erling_haaland,
            R.drawable.ewa_pajor,
            R.drawable.harry_kane,
            R.drawable.jadon_sancho,
            R.drawable.jennifer_hermoso,
            R.drawable.ji_so_yun,
            R.drawable.jordan_henderson,
            R.drawable.joshua_kimmich,
            R.drawable.karim_benzema,
            R.drawable.kevin_de_bruyne,
            R.drawable.kylian_mbappe,
            R.drawable.lionel_messi,
            R.drawable.manuel_neuer,
            R.drawable.marcus_rashford,
            R.drawable.marie_antoinettekatoto,
            R.drawable.mohamed_salah,
            R.drawable.ney_mar,
            R.drawable.paulo_dybala,
            R.drawable.pernille_harder,
            R.drawable.raheem_sterling,
            R.drawable.robert_lewandowski,
            R.drawable.romelu_lukaku,
            R.drawable.sadio_mane,
            R.drawable.sergio_ramos,
            R.drawable.t_axexander_arnold,
            R.drawable.thiago_alcantara,
            R.drawable.thomas_muller,
            R.drawable.trent_alexander_arnold,
            R.drawable.te_o,
            R.drawable.virgil_van_dijk,
            R.drawable.vivianne_miedema,
            R.drawable.wendie_renard
    };

    String[] answers ={
            "Abby Dahlkemper",
            "Alexia Putellas",
            "Alphonso Davies",
            "Amel Majri",
            "Asisat Oshoala",
            "Beth England",
            "Bruno Fernandes",
            "Ciro Immobile",
            "Cristiana Girelli",
            "Cristiano Ronaldo",
            "Erling Haaland",
            "Ewa Pajor",
            "Harry Kane",
            "Jadon Sancho",
            "Jennifer Hermoso",
            "Ji So-yun",
            "Jordan Henderson",
            "Joshua Kimmich",
            "Karim Benzema",
            "Kevin De Bruyne",
            "Kylian Mbappe",
            "Lionel Messi",
            "Manuel Neuer",
            "Marcus Rashford",
            "Marie Antoinette Katoto",
            "Mohamed Salah",
            "Neymar",
            "Paulo Dybala",
            "Pernille Harder",
            "Raheem Sterling",
            "Robert Lewandowski",
            "Romelu Lukaku",
            "Sadio Mane",
            "Sergio Ramos",
            "T Axexander Arnold",
            "Thiago Alcantara",
            "Thomas_Muller",
            "Trent Alexander Arnold",
            "Tèo",
            "Virgil Van Dijk",
            "Vivianne Miedema",
            "Wendie Renard",

    };
}
